### ISSUE TITLE
Starting child process with 'node dist/server.js' /// ReferenceError: version is not defined

### ISSUE THREAD

**Issue by 4rs3nik** [tarkovarmory/tarkovarmory#13]
Hello ! It's been some days that i'm trying to get this working but i can't. Anyone know where is the problem ?

```
PS D:\tarkovarmory-master> npm install
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.

> core-js@2.6.9 postinstall D:\tarkovarmory-master\node_modules\core-js
> node scripts/postinstall || echo "ignore"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon:
> https://opencollective.com/core-js
> https://www.patreon.com/zloirock

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

added 948 packages from 652 contributors and audited 18993 packages in 16.238s

4 packages are looking for funding
  run `npm fund` for details

found 677 vulnerabilities (675 low, 2 moderate)
  run `npm audit fix` to fix them, or `npm audit` for details

```

Then when i launch it, it repeat that infinite times :

```
ReferenceError: version is not defined
    at Object../src/generated.ts (D:\tarkovarmory-master\dist\webpack:\src\generated.ts:1:1)
    at __webpack_require__ (D:\tarkovarmory-master\dist\webpack:\webpack\bootstrap:19:1)
    at Object../src/translate.ts (D:\tarkovarmory-master\dist\webpack:\src\translate.ts:2:1)
    at __webpack_require__ (D:\tarkovarmory-master\dist\webpack:\webpack\bootstrap:19:1)
    at Object../src/Nav.tsx (D:\tarkovarmory-master\dist\webpack:\src\Nav.tsx:5:1)
    at __webpack_require__ (D:\tarkovarmory-master\dist\webpack:\webpack\bootstrap:19:1)
    at Object../src/Main.tsx (D:\tarkovarmory-master\dist\webpack:\src\Main.tsx:7:1)
    at __webpack_require__ (D:\tarkovarmory-master\dist\webpack:\webpack\bootstrap:19:1)
    at Object../src/server.tsx (D:\tarkovarmory-master\dist\webpack:\src\server.tsx:8:1)
    at __webpack_require__ (D:\tarkovarmory-master\dist\webpack:\webpack\bootstrap:19:1)
Program node dist/server.js exited with code 1

Starting child process with 'node dist/server.js'

D:\tarkovarmory-master\dist\webpack:\src\generated.ts:1
version https://git-lfs.github.com/spec/v1
^
ReferenceError: version is not defined
```

**Comment by tarkovarmory** [comment]
That's an LFS tracked file, do you need to do something to pull down git LFS files on your system maybe? https://git-lfs.github.com/ might be of some use
